// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	CardName   string `json:"cardName"`
	CardNumber string `json:"cardNumber"`
	Cvv        string `json:"cvv"`
	ExpiryDate string `json:"expiryDate"`
}

type NewRefreshToken struct {
	Token string `json:"Token"`
}

type NewTransaction struct {
	CardNumber  string `json:"cardNumber"`
	Cvv         string `json:"cvv"`
	Name        string `json:"Name"`
	City        string `json:"City"`
	Country     string `json:"Country"`
	Address     string `json:"Address"`
	PostalCode  string `json:"PostalCode"`
	ExpMonth    int    `json:"ExpMonth"`
	ExpYear     int    `json:"ExpYear"`
	Email       string `json:"Email"`
	PhoneNumber string `json:"PhoneNumber"`
	Amount      string `json:"Amount"`
	Currency    string `json:"Currency"`
	Description string `json:"Description"`
}

type Transaction struct {
	ID               string  `json:"Id"`
	User             *User   `json:"user"`
	TransactionDate  string  `json:"transactionDate"`
	ChargeSuccessful bool    `json:"chargeSuccessful"`
	WalletUpdated    bool    `json:"walletUpdated"`
	TransactionID    *string `json:"TransactionId"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type UserAuth struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
